import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Bot, RefreshCw, AlertCircle, Sparkles } from 'lucide-react';

interface AIInsightsProps {
  campaignId: string;
  insights?: string;
  loading: boolean;
  error?: Error | null;
  onRetry: () => void;
}

export function AIInsights({ insights, loading, error, onRetry }: AIInsightsProps) {
  if (loading) {
    return (
      <Card className="border-blue-200 bg-blue-50/50">
        <CardHeader>
          <div className="flex items-center space-x-2">
            <Bot className="h-5 w-5 text-blue-600 animate-pulse" />
            <CardTitle className="text-blue-800">AI Campaign Analysis</CardTitle>
          </div>
        </CardHeader>
        <CardContent>
          <div className="flex items-center space-x-3 text-blue-700">
            <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-blue-600"></div>
            <span className="text-sm">Generating AI insights...</span>
          </div>
        </CardContent>
      </Card>
    );
  }

  if (error) {
    return (
      <Card className="border-red-200 bg-red-50/50">
        <CardHeader>
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-2">
              <AlertCircle className="h-5 w-5 text-red-600" />
              <CardTitle className="text-red-800">AI Insights Unavailable</CardTitle>
            </div>
            <Button
              variant="outline"
              size="sm"
              onClick={onRetry}
              className="text-red-600 border-red-300 hover:bg-red-100"
            >
              <RefreshCw className="h-4 w-4 mr-1" />
              Retry
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          <Alert className="border-red-200 bg-red-50">
            <AlertDescription className="text-red-700">
              Failed to generate AI insights. This could be due to API limits or connectivity issues. 
              Try again or check your OpenAI configuration.
            </AlertDescription>
          </Alert>
        </CardContent>
      </Card>
    );
  }

  if (!insights) {
    return (
      <Card className="border-gray-200 bg-gray-50/50">
        <CardHeader>
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-2">
              <Bot className="h-5 w-5 text-gray-600" />
              <CardTitle className="text-gray-800">AI Campaign Analysis</CardTitle>
            </div>
            <Button
              variant="outline"
              size="sm"
              onClick={onRetry}
              className="text-gray-600 border-gray-300"
            >
              <Bot className="h-4 w-4 mr-1" />
              Generate Insights
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          <div className="text-center py-4 text-gray-600">
            <Bot className="h-12 w-12 mx-auto mb-2 opacity-50" />
            <p className="text-sm">AI insights not yet generated</p>
            <p className="text-xs text-gray-500 mt-1">Click "Generate Insights" to analyze this campaign</p>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className="border-blue-200 bg-gradient-to-r from-blue-50 to-purple-50">
      <CardHeader>
        <div className="flex items-center space-x-2">
          <div className="flex items-center space-x-2">
            <div className="relative">
              <Bot className="h-5 w-5 text-blue-600" />
              <Sparkles className="h-3 w-3 text-purple-500 absolute -top-1 -right-1" />
            </div>
            <CardTitle className="text-blue-800">AI Campaign Analysis</CardTitle>
          </div>
          <div className="ml-auto">
            <div className="px-2 py-1 bg-blue-100 text-blue-700 text-xs rounded-full font-medium">
              Powered by AI
            </div>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        <div className="bg-white p-4 rounded-lg border border-blue-100 shadow-sm">
          <div className="flex items-start space-x-3">
            <Bot className="h-5 w-5 text-blue-600 mt-0.5 flex-shrink-0" />
            <div className="flex-1">
              <p className="text-gray-800 leading-relaxed">{insights}</p>
              <div className="mt-3 text-xs text-gray-500 flex items-center space-x-2">
                <span>Generated by OpenAI</span>
                <span>•</span>
                <span>{new Date().toLocaleDateString()}</span>
              </div>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}